/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankapplication;

import java.awt.Color;
import javax.swing.SwingConstants;


/**
 *
 * @author Nishikata
 */
public class LoginGUI extends javax.swing.JFrame {
    java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/Images/banklogo.png"));
    Color hoveredColor = new Color(64,216,255);
    Color hoveredOut = new Color(102,204,255);
    Color defaultColor = new Color(204,204,204);
    private final Bank bank = new Bank();
    
    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
    }
    
    private void Login (){
         try{
            String username = inputUser.getText();
            String password = new String(inputPass.getPassword());
            if(!username.isBlank() || !password.isBlank()){
                User user = bank.findUser(username);
                if(user.getPassword().equals(password)){
                    BankingGUI landingpage = new BankingGUI(user);
                    landingpage.setLocationRelativeTo(this);
                    landingpage.setVisible(true);
                    this.dispose();
                } else {
                    throw new NullPointerException();
                }
            } else {
                bank.failed(warningLabel, "Empty input.");
            }
        } catch (NullPointerException e){
            bank.failed(warningLabel, "Incorrect Credentials");
        } catch (Exception e){
            System.out.println("NEW ERROR " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        inputUser = new javax.swing.JTextField();
        userSeparator = new javax.swing.JSeparator();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        passSeparator = new javax.swing.JSeparator();
        inputPass = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Davao Bank");
        setFocusCycleRoot(false);
        setIconImage(icon);
        setUndecorated(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 400));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Bank Image.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addGap(0, 0, 0))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 90));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("Welcome");

        close_btn.setBackground(new java.awt.Color(255, 102, 102));
        close_btn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setText("X");
        close_btn.setBorderPainted(false);
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.setFocusPainted(false);
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBtnHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBtnHoverOut(evt);
            }
        });
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(close_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 145));

        inputUser.setBorder(null);
        inputUser.setPreferredSize(new java.awt.Dimension(200, 30));
        inputUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputUserFocusLost(evt);
            }
        });
        inputUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputUserKeyPressed(evt);
            }
        });

        userSeparator.setBackground(new java.awt.Color(204, 204, 204));
        userSeparator.setForeground(new java.awt.Color(204, 204, 204));

        userLabel.setBackground(new java.awt.Color(255, 255, 255));
        userLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        userLabel.setText("Username");

        passLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        passLabel.setText("Password");

        passSeparator.setBackground(new java.awt.Color(204, 204, 204));
        passSeparator.setForeground(new java.awt.Color(204, 204, 204));

        inputPass.setBorder(null);
        inputPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passInput(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passInputfocus(evt);
            }
        });
        inputPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPassActionPerformed(evt);
            }
        });
        inputPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userSeparator, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(inputPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(passSeparator, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(userLabel)
                .addGap(0, 0, 0)
                .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(userSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(passSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(350, 130));

        loginBtn.setBackground(new java.awt.Color(102, 204, 255));
        loginBtn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setBorder(null);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setFocusPainted(false);
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Hover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HoverOut(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Don't have an account yet?");

        createBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        createBtn.setForeground(new java.awt.Color(102, 204, 255));
        createBtn.setText("Create Account");
        createBtn.setBorder(null);
        createBtn.setBorderPainted(false);
        createBtn.setContentAreaFilled(false);
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.setFocusPainted(false);
        createBtn.setFocusable(false);
        createBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createBtn.setRequestFocusEnabled(false);
        createBtn.setRolloverEnabled(false);
        createBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkHoverIn(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkHoverOut(evt);
            }
        });
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 51, 51));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createBtn)
                .addGap(0, 76, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(warningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(createBtn))
                .addGap(0, 0, 0))
        );

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
       Login();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void Hover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hover
        // TODO add your handling code here:
        loginBtn.setBackground(hoveredColor);
    }//GEN-LAST:event_Hover

    private void HoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoverOut
        // TODO add your handling code here:
        loginBtn.setBackground(hoveredOut);
    }//GEN-LAST:event_HoverOut

    private void linkHoverIn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkHoverIn
        // TODO add your handling code here:
        createBtn.setForeground(Color.red);
    }//GEN-LAST:event_linkHoverIn

    private void linkHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkHoverOut
        // TODO add your handling code here:
        createBtn.setForeground(hoveredOut);
    }//GEN-LAST:event_linkHoverOut

    private void inputUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUserFocusGained
        // TODO add your handling code here:
        inputUser.setForeground(hoveredColor);
        userLabel.setForeground(Color.BLACK);
        userSeparator.setForeground(Color.BLACK);
        userSeparator.setBackground(hoveredColor);
    }//GEN-LAST:event_inputUserFocusGained

    private void inputUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUserFocusLost
        // TODO add your handling code here:
         inputUser.setForeground(defaultColor);
         userLabel.setForeground(defaultColor);
         userSeparator.setForeground(defaultColor);
         userSeparator.setBackground(defaultColor);

    }//GEN-LAST:event_inputUserFocusLost

    private void passInput(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passInput
        // TODO add your handling code here:
        inputPass.setForeground(hoveredColor);
        passLabel.setForeground(Color.BLACK);
        passSeparator.setForeground(Color.BLACK);
        passSeparator.setBackground(hoveredColor);
    }//GEN-LAST:event_passInput

    private void passInputfocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passInputfocus
        // TODO add your handling code here:
        inputPass.setForeground(defaultColor);
        passLabel.setForeground(defaultColor);
        passSeparator.setForeground(defaultColor);
        passSeparator.setBackground(defaultColor);
    }//GEN-LAST:event_passInputfocus

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        RegisterGUI register = new RegisterGUI();
        register.setLocationRelativeTo(this);
        register.setVisible(true);
        dispose();
    }//GEN-LAST:event_createBtnActionPerformed

    private void inputPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPassActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void exitBtnHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnHover
        // TODO add your handling code here:
        close_btn.setBackground(new Color(255,0,0));
        
    }//GEN-LAST:event_exitBtnHover

    private void exitBtnHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnHoverOut
        // TODO add your handling code here:
        close_btn.setBackground(new Color(255,102,102));
    }//GEN-LAST:event_exitBtnHoverOut

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void inputUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputUserKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            Login();
        }
    }//GEN-LAST:event_inputUserKeyPressed

    private void inputPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            Login();
        }
    }//GEN-LAST:event_inputPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close_btn;
    private javax.swing.JButton createBtn;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel passLabel;
    private javax.swing.JSeparator passSeparator;
    private javax.swing.JLabel userLabel;
    private javax.swing.JSeparator userSeparator;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
