/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankapplication;
import java.awt.Color;
/**
 *
 * @author Nishikata
 */
public class RegisterGUI extends javax.swing.JFrame {
     java.awt.Image icon = java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/Images/banklogo.png"));
    Color hoveredColor = new Color(64,216,255);
    Color hoveredOut = new Color(102,204,255);
    Color defaultColor = new Color(204,204,204);
    Color closeColor = new Color(255,0,0);
    Color closeDefault = new Color(255,102,102);
    private Bank bank = new Bank();
    /**
     * Creates new form RegisterGUI
     */
    public RegisterGUI() {
        initComponents();
    }

    private void Register() {
        String name = name_input.getText();
        String username = username_input.getText();
        String password = new String(password_input.getPassword());
        String confirmpass = new String(confirmpass_input.getPassword());
        
        if(!name.isBlank() && !username.isBlank() && !password.isBlank()){
            if(!password.equals(confirmpass)){
                bank.failed(warningLabel, "Password do not match.");
                return;
            }
            boolean register = bank.registerUser(name, username, password);
            if(register){
                bank.failed(warningLabel, "Registration Successfull");
                LoginGUI login = new LoginGUI();
                login.setLocationRelativeTo(this);
                login.setVisible(true);
                dispose();
            } else {
                bank.failed(warningLabel, "Username already exists.");
            }
        } else {
            bank.failed(warningLabel, "Empty input.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        close_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        confirmpass_label = new javax.swing.JLabel();
        confirmpass_input = new javax.swing.JPasswordField();
        name_separator = new javax.swing.JSeparator();
        username_separator = new javax.swing.JSeparator();
        password_separator = new javax.swing.JSeparator();
        confirmpass_separator = new javax.swing.JSeparator();
        cancel_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Davao Bank");
        setIconImage(icon);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 400));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Images/Bank Image.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        close_btn.setBackground(new java.awt.Color(255, 102, 102));
        close_btn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setText("X");
        close_btn.setBorderPainted(false);
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.setFocusPainted(false);
        close_btn.setPreferredSize(new java.awt.Dimension(42, 28));
        close_btn.setVerifyInputWhenFocusTarget(false);
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_btnexitBtnHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_btnexitBtnHoverOut(evt);
            }
        });
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Create Account");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        name_label.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        name_label.setText("Name");

        name_input.setBorder(null);
        name_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocus(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        name_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name_inputKeyPressed(evt);
            }
        });

        username_label.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        username_label.setText("Username");

        username_input.setBorder(null);
        username_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unameFocus(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unameFocusLost(evt);
            }
        });
        username_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_inputKeyPressed(evt);
            }
        });

        password_label.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        password_label.setText("Password");

        password_input.setBorder(null);
        password_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocus(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        password_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_inputKeyPressed(evt);
            }
        });

        confirmpass_label.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        confirmpass_label.setText("Confirm Password");

        confirmpass_input.setBorder(null);
        confirmpass_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conpassFocus(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                conpassFocusLost(evt);
            }
        });
        confirmpass_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                confirmpass_inputKeyPressed(evt);
            }
        });

        name_separator.setBackground(new java.awt.Color(204, 204, 204));
        name_separator.setForeground(new java.awt.Color(204, 204, 204));

        username_separator.setBackground(new java.awt.Color(204, 204, 204));
        username_separator.setForeground(new java.awt.Color(204, 204, 204));

        password_separator.setBackground(new java.awt.Color(204, 204, 204));
        password_separator.setForeground(new java.awt.Color(204, 204, 204));

        confirmpass_separator.setBackground(new java.awt.Color(204, 204, 204));
        confirmpass_separator.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name_separator, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(username_label)
                    .addComponent(username_separator)
                    .addComponent(username_input, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(name_label)
                    .addComponent(name_input)
                    .addComponent(password_label)
                    .addComponent(confirmpass_label)
                    .addComponent(password_input)
                    .addComponent(confirmpass_input)
                    .addComponent(password_separator)
                    .addComponent(confirmpass_separator))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(name_separator, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(username_separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(password_separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmpass_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmpass_input, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(confirmpass_separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        cancel_btn.setBackground(new java.awt.Color(255, 102, 102));
        cancel_btn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("Cancel");
        cancel_btn.setBorder(null);
        cancel_btn.setBorderPainted(false);
        cancel_btn.setFocusPainted(false);
        cancel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelHoverOut(evt);
            }
        });
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        submit_btn.setBackground(new java.awt.Color(102, 204, 255));
        submit_btn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.setBorder(null);
        submit_btn.setBorderPainted(false);
        submit_btn.setFocusPainted(false);
        submit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitHoverOut(evt);
            }
        });
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));
        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnexitBtnHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnexitBtnHover
        // TODO add your handling code here:
        close_btn.setBackground(closeColor);

    }//GEN-LAST:event_close_btnexitBtnHover

    private void close_btnexitBtnHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnexitBtnHoverOut
        // TODO add your handling code here:
        close_btn.setBackground(closeDefault);
    }//GEN-LAST:event_close_btnexitBtnHoverOut

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void userFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocus
        // TODO add your handling code here:
        name_label.setForeground(Color.BLACK);
        name_input.setForeground(hoveredColor);
        name_separator.setForeground(Color.BLACK);
        name_separator.setBackground(hoveredColor);
        
    }//GEN-LAST:event_userFocus

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        // TODO add your handling code here:
        name_label.setForeground(defaultColor);
        name_input.setForeground(defaultColor);
        name_separator.setForeground(defaultColor);
        name_separator.setBackground(defaultColor);
    }//GEN-LAST:event_userFocusLost

    private void unameFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameFocus
        // TODO add your handling code here:
        username_label.setForeground(Color.BLACK);
        username_input.setForeground(hoveredColor);
        username_separator.setForeground(Color.BLACK);
        username_separator.setBackground(hoveredColor);
    }//GEN-LAST:event_unameFocus

    private void unameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameFocusLost
        // TODO add your handling code here:
        username_label.setForeground(defaultColor);
        username_input.setForeground(defaultColor);
        username_separator.setForeground(defaultColor);
        username_separator.setBackground(defaultColor);
    }//GEN-LAST:event_unameFocusLost

    private void passFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocus
        // TODO add your handling code here:
        password_label.setForeground(Color.BLACK);
        password_input.setForeground(hoveredColor);
        password_separator.setForeground(Color.BLACK);
        password_separator.setBackground(hoveredColor);
    }//GEN-LAST:event_passFocus

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        // TODO add your handling code here:
        password_label.setForeground(defaultColor);
        password_input.setForeground(defaultColor);
        password_separator.setForeground(defaultColor);
        password_separator.setBackground(defaultColor);
    }//GEN-LAST:event_passFocusLost

    private void conpassFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conpassFocus
        // TODO add your handling code here:
        confirmpass_label.setForeground(Color.BLACK);
        confirmpass_input.setForeground(hoveredColor);
        confirmpass_separator.setForeground(Color.BLACK);
        confirmpass_separator.setBackground(hoveredColor);
    }//GEN-LAST:event_conpassFocus

    private void conpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conpassFocusLost
        // TODO add your handling code here:
        confirmpass_label.setForeground(defaultColor);
        confirmpass_input.setForeground(defaultColor);
        confirmpass_separator.setForeground(defaultColor);
        confirmpass_separator.setBackground(defaultColor);
    }//GEN-LAST:event_conpassFocusLost

    private void cancelHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelHover
        // TODO add your handling code here:
        cancel_btn.setBackground(closeColor);
    }//GEN-LAST:event_cancelHover

    private void cancelHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelHoverOut
        // TODO add your handling code here:
        cancel_btn.setBackground(closeDefault);
    }//GEN-LAST:event_cancelHoverOut

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
       LoginGUI login = new LoginGUI();
       login.setLocationRelativeTo(this);
       login.setVisible(true);
       dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void submitHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitHover
        // TODO add your handling code here:
        submit_btn.setBackground(hoveredColor);
    }//GEN-LAST:event_submitHover

    private void submitHoverOut(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitHoverOut
        // TODO add your handling code here:
        submit_btn.setBackground(hoveredOut);
    }//GEN-LAST:event_submitHoverOut

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        Register();
    }//GEN-LAST:event_submit_btnActionPerformed

    private void name_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_inputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
           Register(); 
        }
    }//GEN-LAST:event_name_inputKeyPressed

    private void username_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_inputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            Register();
        }
    }//GEN-LAST:event_username_inputKeyPressed

    private void password_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_inputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            Register();
        }
    }//GEN-LAST:event_password_inputKeyPressed

    private void confirmpass_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_confirmpass_inputKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            Register();
        }
    }//GEN-LAST:event_confirmpass_inputKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JPasswordField confirmpass_input;
    private javax.swing.JLabel confirmpass_label;
    private javax.swing.JSeparator confirmpass_separator;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel name_label;
    private javax.swing.JSeparator name_separator;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel password_label;
    private javax.swing.JSeparator password_separator;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_label;
    private javax.swing.JSeparator username_separator;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
